00 PyTorch Fundamentals
Reference Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [3]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2


# Introduction to Tensors

## Creating Tensors

PyTorch Tensors are created using `torch.tensor()` 

In [4]:

# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get Tensor back as Python Int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch Random Tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [29]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5561, 0.7594, 0.1925, 0.7863],
        [0.5428, 0.5600, 0.3169, 0.3204],
        [0.5192, 0.8887, 0.7413, 0.0448]])

In [30]:
random_tensor.ndim

2

In [31]:
# Random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

# The common way of formatting images is with 224x224 pixels, and the 3 color channels (rgb) is for its tensor translation

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensors

In [32]:
# A tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# A tensor of all ones 
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
# Datatype
ones.dtype 

torch.float32

### Creating a Range of Tensors and Tensors-like

In [40]:
# Use torch.arange() since torch.range() is deprecated
one_to_ten = torch.arange(0, 21, 2) # start, end, step
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
# Creating tensors-like to make similar tensors as the input
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch and Deep Learning. These errors are:
1. Tensors are not the right datatype --> (`tensor.dtype`)
2. Tensors are not the right shape --> (`tensor.shape`)
3. Tensors are not on the right device --> (`tensor.device`)


In [43]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Tensor data type (e.g float32 or float64)
                               device=None, # Device tensor is on
                               requires_grad=False) # Whether or not to track gradients with tensor operations
float_32_tensor


tensor([3., 6., 9.])

In [44]:
float_32_tensor.dtype

torch.float32

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [48]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [49]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [50]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors (Tensor Attributes)

In [57]:
some_tensor = torch.rand(3, 4)
some_tensor = some_tensor.type(torch.half)
some_tensor

tensor([[0.9932, 0.3484, 0.0576, 0.5693],
        [0.7373, 0.9814, 0.1699, 0.9795],
        [0.4651, 0.7417, 0.4441, 0.1461]], dtype=torch.float16)

In [58]:
# Finding out details
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.9932, 0.3484, 0.0576, 0.5693],
        [0.7373, 0.9814, 0.1699, 0.9795],
        [0.4651, 0.7417, 0.4441, 0.1461]], dtype=torch.float16)
Datatype of Tensor: torch.float16
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor Operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Matrix Multiplication
- Division

In [62]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor += 10
tensor

tensor([11, 12, 13])

In [63]:
# Multiplication
tensor *= 10
tensor

tensor([110, 120, 130])

In [64]:
# Subtraction
tensor -= 2
tensor

tensor([108, 118, 128])

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy (@ is a form to represent matmul):
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix will have the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> (2, 2)
* `(3, 2) @ (2, 3)` -> (3, 3)

In [66]:
# Element-wise multiplication
print(tensor,  "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([108, 118, 128]) * tensor([108, 118, 128])
Equals: tensor([11664, 13924, 16384])


In [75]:
# Matrix multiplication (highly encouraged since doing this by hand is very lengthy)
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

tensor(14)

In [90]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 634 µs, sys: 627 µs, total: 1.26 ms
Wall time: 770 µs


In [95]:
%%time
# Time is printed to show how quicker it is to use the matmul method
torch.matmul(tensor, tensor)

CPU times: user 149 µs, sys: 42 µs, total: 191 µs
Wall time: 177 µs


tensor(14)

### One of the most common errors in Deep Learning: Shape Errors

In [96]:
# Shapes for Matrix Multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given tensor. 

In [97]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [98]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [99]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [101]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above, tensor_B.T = {tensor_B.T})\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above, tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]]))

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [102]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [103]:
# Find the min 
torch.min(x), x.min()

(tensor(0), tensor(0))

In [104]:
# Find the max 
torch.max(x), x.max()

(tensor(90), tensor(90))

In [107]:
# Find the mean (torch.mean() requires a tensor of float32 datatype to work)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [108]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Find the positional min and max

In [109]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [110]:
# Find the position in tensor that has the maximum value
x.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

* Reshaping: Reshapes an input tensor to a defined shape
* View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: Removes all `1` dimensions from a tensor
* Unsqueeze: Add a `1` dimensions to a target tensor
* Permute: Return a view of the input with dimensions permuted (swapped) in a certain way

In [111]:
# New tensor, regardless of the previous cell blocks
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [112]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [113]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [114]:
# Changing z changes x because a view of a tensor shares teh same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [123]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [130]:
# torch.squeeze() removes all single dimensions from a target tensor
x_reshaped = x_reshaped.reshape(1, 9) # Also try with commenting out this line
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [134]:
# torch.unsqueeze() adds a single dimension to a target tensor at a specific dimension

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # Try with dim=1 too
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, color_channels)

# Permute the original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # (color_channels, height, width)

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [135]:
# Create a new tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [136]:
# Let's index of our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [137]:
# Index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [139]:
# Index on the most inner bracket (last dimension)
x[0][0][0]

tensor(9)

In [145]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [141]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [146]:
# Get all values of the 0 dimensions but only the 1 index value of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [147]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimensions
x[0, 0, :]

tensor([1, 2, 3])

In [152]:
# Index on x to return 9
x[:, 2, 2]
# Index on x to retun [3, 6, 9]
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch Tensors and NumPy

NumPy is a popular scientific Python numerical computing library. Consequently, PyTorch has functionality to interact with it.

* Transforming Data in NumPy into a Tensor in PyTorch -> `torch.from_numpy(ndarray)`
* Transforming from PyTorch Tensor into NumPy data -> `torch.Tensor.numpy()`

In [159]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # When converting from NumPy to PyTorch, PyTorch reflects NumPy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [165]:
# Change the value of array. What will this do to the tensor? They don't share memory
array += 1
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([3., 3., 3., 3., 3., 3., 3.]))

In [161]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [166]:
# Change the tensor. What happens to the numpy_tensor? They share memory
tensor += 1
tensor, numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([4., 4., 4., 4., 4., 4., 4.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short, how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in Neural Networks and PyTorch comes the concept of a **random seed**. Essentially, the random seed "flavors" the randomness through pseudo-randomness. 

In [167]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7496, 0.1025, 0.3819, 0.4155],
        [0.6534, 0.6185, 0.9671, 0.5524],
        [0.2512, 0.3547, 0.6706, 0.6221]])
tensor([[0.6872, 0.0843, 0.8088, 0.6081],
        [0.2222, 0.4735, 0.0747, 0.2238],
        [0.9983, 0.7395, 0.4616, 0.2810]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [168]:
# Random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # The seed has to be reset every time an operation is performed
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (making faster computations)

GPUs -> faster computations on numbers due to CUDA + NVIDIA hardware + PyTorch working behind the scenes

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU, takes a little bit of setup and requires the investment of purchasing a GPU. Here is a post covering this: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure. These services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setup. To do this, refer to PyTorch documentation: https://pytorch.org/get-started/locally/

In [182]:
# This can be used to see if the GPU is setup (on Google Colab this is already done, to run locally it has to be setup)
import torch
torch.cuda.is_available() 

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [183]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [184]:
# Count the number of devices
torch.cuda.device_count()

0

### Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [185]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [186]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to the CPU

In [187]:
# If tensor is on GPU, it cannot be transformed to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [188]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])